### ISSUE TITLE
Improve default for metabolic rate

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#101]
Currently, if the coefficient `ks` of the allometric metabolic rate is not given in the species parameters, it is set to `0.2 * h`. Given that the coefficient of the allometric growth rate is `alpha * feeding_level * h - ks`, species will not grow unless `alpha * feeding_level > 0.2`. Would it perhaps be more appropriate to set `ks` to `0.5 * alpha * feeding_level * h` so that only half of the consumption is lost to metabolism? Any advice @Kenhasteandersen @juliablanchard @astaaudzi ?

**Comment by Kenhasteandersen** [comment]
IWould it perhaps be more appropriate to set ks to 0.5 * alpha * feeding_level * h so that only half of the consumption is lost to metabolism? Any advice @Kenhasteandersen<https://github.com/Kenhasteandersen> @juliablanchard<https://github.com/juliablanchard> @astaaudzi<https://github.com/astaaudzi> ?

I’m not quite sure I understand what you ask. When you write “feeding_level”, is it then “f(w, t)”, or the constant “f_0”? It is important that the metabolism is a constant and not a dynamic function of the feeding level. There are two losses: 1) assimilation, which is a fraction of consumption, represented by alpha; 2) standard metabolism, which is independent of consumption.

Ken

**Comment by gustavdelius** [comment]
@Kenhasteandersen , what I am looking for is a good default value for `ks`. I believe the philosophy of mizer is that when people have only partial knowledge of their species, i.e., only know some of the parameters, mizer tries to provide defaults for the unknown parameters in such a way that the species is at least viable. The current choice of `ks = 0.2 * h` does not do that. Assume for example that it is known that the species has a low assimilation efficiency of `alpha = 0.1`. In that case the current default for `ks` says that the species has a higher metabolic demand than it could ever cover by feeding. Such a species would never have evolved. So I am looking for a better default value for `ks`.

Do you know what the motivation for the choice `ks = 0.2 * h` was?

**Comment by Kenhasteandersen** [comment]
Got it. Yes, the correct rule would be: ks = f_c*alpha*h, where f_c approx 0.2 is the critical feeding level. The value “0.2” is  rule of thumb. When I wrote the book I tried to make a data analysis to derive it, but it did not work out very well. I’ve attached the pages where I discuss this.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:50afd584-2091-4184-a2a6-995288d20920@win.dtu.dk]

On 17 Sep 2019, at 08.40, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kenhasteandersen<https://github.com/Kenhasteandersen> , what I am looking for is a good default value for ks. I believe the philosophy of mizer is that when people have only partial knowledge of their species, i.e., only know some of the parameters, mizer tries to provide defaults for the unknown parameters in such a way that the species is at least viable. The current choice of ks = 0.2 * h does not do that. Assume for example that it is known that the species has a low assimilation efficiency of alpha = 0.1. In that case the current default for ks says that the species has a higher metabolic demand than it could ever cover by feeding. Such a species would never have evolved. So I am looking for a better default value for ks.

Do you know what the motivation for the choice ks = 0.2 * h was?

**Comment by gustavdelius** [comment]
Good. I'll change the default in the new version to `ks = 0.2 * alpha * h` then. I will also add a warning when a user has specified a value for `f0` that is less than the critical feeding level of `0.2`.

**Comment by Kenhasteandersen** [comment]
Hmm. Setting p != n is a little tricky because it introduces some extra effect. In that case it might be better not to set a default, but force the user to reflect upon what it means in terms of the value of ks.

If you think that we should have a default, then your suggestion is ok.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:image001.jpg@01D09493.A377DFB0]

On 17 Sep 2019, at 10.07, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


Or how about setting the default to ks = 0.2 * alpha * h * w_mat^(n-p) so that the critical feeding level is equal to 0.2 at w_mat also when n != p?

**Comment by gustavdelius** [comment]
@Kenhasteandersen , I agree with you that it is tricky to give good defaults when `p != n`. For example the default for `h` that leads to the right maturity age will become difficult. We should definitely issue a stark warning when we provide any defaults for this case. However I would like mizer to provide _some_ default so that the user can then use shiny gadgets to start investigating the system and interactively explore better parameter values. All I require of the defaults for that purpose is that they allow every species to reach maturity size in order to have some reproduction.

**Comment by Kenhasteandersen** [comment]
Seems good to me.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:image001.jpg@01D09493.A377DFB0]

On 17 Sep 2019, at 11.19, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kenhasteandersen<https://github.com/Kenhasteandersen> , I agree with you that it is tricky to give good defaults when p != n. For example the default for h that leads to the right maturity age will become difficult. We should definitely issue a stark warning when we provide any defaults for this case. However I would like mizer to provide some default so that the user can then use shiny gadgets to start investigating the system and interactively explore better parameter values. All I require of the defaults for that purpose is that they allow every species to reach maturity size in order to have some reproduction.
