### ISSUE TITLE
How to combine plots for different simulations

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#105]
Often one will want to combine the result of two different simulations on the same plot, for example to compare the consequences of different fishing regimes. This is not easy to achieve with mizer's existing plot functions. I have played with two different approaches to solving this problem:

1. Allowing an optional second MizerSim object to be passed to a plotting function, see [`plotYield()`](https://sizespectrum.org/mizer/dev/reference/plotlyYield.html).
2. Creating functions that return the dataframe needed to produce the plot, rather than the plot itself, see [`getBiomassFrame()`](https://sizespectrum.org/mizer/dev/reference/getBiomassFrame.html) and [`getSSBFrame()`](https://sizespectrum.org/mizer/dev/reference/getSSBFrame.html), and then providing a function [`displayFrames()`](https://sizespectrum.org/mizer/dev/reference/displayFrames.html) that takes two of these frames and plots them.

Neither of these are perfect, so please make your own suggestions.

We should probably settle on one approach and then implement it consistently for all plotting functions where it is appropriate.

**Comment by Kenhasteandersen** [comment]
Hi Gustav,

I have used the first option myself in my own code. It has worked well for me.

I am working on the stomach size-distribution problem. Almost there.

Ken
---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:image001.jpg@01D09493.A377DFB0]

On 17 Sep 2019, at 16.41, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


Often one will want to combine the result of two different simulations on the same plot, for example to compare the consequences of different fishing regimes. This is not easy to achieve with mizer's existing plot functions. I have played with two different approaches to solving this problem:

  1.  Allowing an optional second MizerSim object to be passed to a plotting function, see plotYield()<https://sizespectrum.org/mizer/dev/reference/plotlyYield.html>.
  2.  Creating functions that return the dataframe needed to produce the plot, rather than the plot itself, see getBiomassFrame()<https://sizespectrum.org/mizer/dev/reference/getBiomassFrame.html> and getSSBFrame()<https://sizespectrum.org/mizer/dev/reference/getSSBFrame.html>, and then providing a function displayFrames()<https://sizespectrum.org/mizer/dev/reference/displayFrames.html> that takes two of these frames and plots them.

Neither of these are perfect, so please make your own suggestions.

We should probably settle on one approach and then implement it consistently for all plotting functions where it is appropriate.

**Comment by gustavdelius** [comment]
@Kenhasteandersen , which plotting functions did you implement option 1 for? Do you want to share your code? Did you do it more elegantly than how it is done for `plotYield()`, which contains a lot of code duplication?

**Comment by Kenhasteandersen** [comment]
I did it in matlab. Not very elegantly, though. However, I like the idea of the functional call that can produce different plots depending on the number of simulation runs that are supplied.

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:image001.jpg@01D09493.A377DFB0]

On 19 Sep 2019, at 09.31, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


@Kenhasteandersen<https://github.com/Kenhasteandersen> , which plotting functions did you implement option 1 for? Do you want to share your code? Did you do it more elegantly than how it is done for plotYield(), which contains a lot of code duplication?

**Comment by gustavdelius** [comment]
For now I have moved the `displayFrame()` function for displaying several frames in the same plot to the mizerExperimental extension package (https://sizespectrum.org/mizerExperimental/), where we can experiment until we find the best way to provide this functionality.

**Comment by gustavdelius** [comment]
It may also be worthwhile to say that we now have a section in the user guide that discusses how to make plots comparing results from two different simulations: https://sizespectrum.org/mizer/dev/articles/plotting.html#comparing-simulations

**Comment by gustavdelius** [comment]
Another development on this front is that @baldrech is going to give an extra argument to the plotting functions to allow them to return a data frame suitable for use with ggplot2 instead of the plot itself. These could then be used to create plots combining several such data frames.

**Comment by gustavdelius** [comment]
@baldrech 's `return_data` argument to all plotting functions that makes them return a data frame together with the new `plotDataFrame()` function now makes `displayFrames()` and the `get...Frame()` functions obsolete and they have been removed from MizerExperimental.
