### ISSUE TITLE
Stop referring to relationship between reproduction and eggs as stock-recruitment relationship

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#143]
Mizer allows the user to impose a non-linear relationship between the energy invested into reproduction and the number of eggs produced. In the mizer documentation this is currently referred to as "stock-recruitment relationship", even though it is only one of the factors contributing to the relationship between the spawning stock biomass and the recruitment. Other important factors are the energy income of the spawners and the mortality of the larvae, both of which are non-linear in mizer.

So I propose to change the wording in the documentation and refer to the relationship between the rate at which energy is invested into reproduction and the rate at which spawning eggs are produced as the "reproduction-egg relationship". Can anyone come up with a better name for it?

Please let me know your views.

**Comment by juliablanchard** [comment]
What about ‘total egg production’ or “reproductive potential” – this terms are both used in fisheries
https://onlinelibrary.wiley.com/doi/full/10.1111/faf.12327
https://onlinelibrary.wiley.com/doi/10.1002/9781118752739.ch11

**Comment by gustavdelius** [comment]
Hi Julia @juliablanchard , those are very useful suggestions. How can we modify those terms to make it clear that we are referring to the relationship between investment into reproduction and the resulting egg production, rather than the egg production itself? Similar to how people use "stock-recruitment relationship" rather than just "recruitment".

**Comment by astaaudzi** [comment]
Hi @gustavdelius. I wonder whether we really need to change this term? I think the stock-recruitment relationship is quite commonly used in this context also in other multispecies models (e.g. Atlantis), even though there are other factors that determine final recruitment. Since we are using Beverton-Holt or Ricker equations to scale egg production into what goes into the first size class, stock-recruitment relationship seems a logical name. I suppose the main difference is that in fisheries this term is used to refer to recruitment into fisheries (so much bigger size), whereas in mizer it is recruitment into the first size class. But the first size class still can be bigger than the egg size, so there is still this all the uncertainty at what happens between egg production and recruitment that gets pooled into the stock-recruitment relationship. Or did I misunderstand the point?

**Comment by gustavdelius** [comment]
Hi @astaaudzi , the point is that the term "stock-recruitment relationship" has a very definite meaning in fisheries science. Using this same term for the relationship between reproductive investment and spawning eggs in mizer is leading to confusion. But your post suggests a possible solution: where currently in the mizer documentation we refer to the "stock-recruitment relationship" we could refer to the "additional contribution to the stock-recruitment relationship" or "external contribution to the stock-recruitment relationship". That reflects the point you were making that we use it to include stock-recruitment effects that are not currently captured by the model.

**Comment by Kenhasteandersen** [comment]
I am not quite sure which relationship you are referring to.  Is it the Beverton-Holt relation? In that case, I suggest we keep the same terminology is usual and call it a “stock-recruitment relation” (SRR).  Technically speaking, it is different than the standard fisheries science term. In fisheries science the SRR is the relationship between spawning stock biomass and recruits; in Mizer it is the relationship between the number of eggs produced and recruits. Nevertheless, the function is the same, namely to introduce additional external density dependence. Using another name will just make it even more difficult for people come from standard fisheries science to get “into” mizer. If we should choose another name it might rather be something along the lines of external density dependence, because this is the main function.

However, if you refer to a non-linear relationship between energy invested and eggs produced, then it is another matter.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:image001.jpg@01D09493.A377DFB0]

On 24 Feb 2020, at 06.58, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi @astaaudzi<https://github.com/astaaudzi> , the point is that the term "stock-recruitment relationship" has a very definite meaning in fisheries science. Using this same term for the relationship between reproductive investment and spawning eggs in mizer is leading to confusion. But your post suggests a possible solution: where currently in the mizer documentation we refer to the "stock-recruitment relationship" we could refer to the "additional contribution to the stock-recruitment relationship" or "external contribution to the stock-recruitment relationship". That reflects the point you were making that we use it to include stock-recruitment effects that are not currently captured by the model.

**Comment by gustavdelius** [comment]
Hi @Kenhasteandersen , I am referring to the non-linear relationship in mizer between energy invested and eggs produced. It is specified via the function in the `@srr` slot in the MizerParams object. Of course it contributes to the stock recruitment relationship that emerges in mizer, but is only one contributing factor. Calling that one contribution itself "the stock recruitment relationship" is misleading. Would it be fine if we describe the function in the `@srr` slot as the "external contribution to the stock-recruitment relationship"? This is meant  to indicate that it is there to capture those contributions to the stock-recruitment relationship that are not due to the trophic interactions modelled in mizer.

**Comment by astaaudzi** [comment]
@gustavdelius the srr relationship in mizer is not really "external" I think, because it describes density dependent processes related to one species only (although they can still be driven by external factors of course). If we call it "external" it could be understood that recruitment is dependent directly on external factors, such as resource abundance or temperature or abundance of other species. 
However, as @juliablanchard mentioned earlier this is actually egg production - recruitment relationship, not stock-recruitment relationship. There are some stock assessment papers that tried to relate recruitment to egg production rather than stock biomass alone (this would presumably better account for the fact that one gram of biomass in a stock consisting of medium sized individuals is not the same as the same gram in a stock with full size diversity). If egg production scales linearly with stock biomass then these two are the same, but at the moment mizer allows non-linear scaling, correct? 

Sorry, still no clear answer from my side. But can it be egg production - recruitment relationship?

**Comment by gustavdelius** [comment]
Hi @astaaudzi . Thank you for your comment. It is really difficult to find terminology that is clear to everyone. I would have thought of resource abundances and abundance of other species as _internal_ because they are things that we model explicitly. By _external_ I had meant factors that are not modelled, like carrying capacity of spawning grounds for example.  

The relationship we are talking about, the one that is implemented via the `@srr` slot in mizer is not an egg production - recruitment relationship. It is a relationship between energy invested into reproduction and the number of eggs. In mizer there are three contributors to the stock-recruitment relationship:
1. The rate at which spawners put energy into reproduction, which is density dependent due to the dependence on the food income of the spawners.
2. The conversion between energy for reproduction and the number of eggs placed into the smallest size class, which is non-linear according to the function in the `@srr` slot.
3. The survivorship from egg size to recruitment size, which is non-linear due to its dependence both on the food intake of the larvae and the predation by larger fish.

We are looking for a name for the 2nd contribution in this list.

**Comment by gustavdelius** [comment]
Can you please check whether you are all o.k. with how I describe the density depence in reproduction in the user guide: https://sizespectrum.org/mizer/articles/model_description.html#density-dependence-in-reproduction ?

**Comment by Kenhasteandersen** [comment]
Looks good to me! Ken
---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

Try my Corona Quarantine Simulator: http://oceanlife.dtuaqua.dk/Corona/

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html



[cid:image001.jpg@01D09493.A377DFB0]

On 2 Apr 2020, at 13.25, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:



Can you please check whether you are all o.k. with how I describe the density depence in reproduction in the user guide: https://sizespectrum.org/mizer/articles/model_description.html#density-dependence-in-reproduction ?

**Comment by juliablanchard** [comment]
Looks great,  just a few minor suggested edits from me.

**Comment by gustavdelius** [comment]
@juliablanchard Hi Julia, thank you very much for making the edits! Please do that anywhere else in the documentation whenever you can. That is very helpful.

**Comment by astaaudzi** [comment]
Hi Gustav,

Looks good to me. One possible correction could be, instead of saying

“… is represented by a reproduction rate Ri (numbers per time) that approaches a maximum as the energy invested in reproduction increases…”

it might be good to be explicit that it is species and not individual’s energy invested in reproduction that increases. Just to be very clear and avoid confusion with increasing investment in reproduction through size

Also “where Rmax.i is the maximum reproduction rate of each trait class” can be a be hard to understand, I mean the term “trait class”. Would it make sense to say “species or trait class”

Regards
Asta
