### ISSUE TITLE
Accessor functions for slots in MizerParams and MizerSim objects

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#145]
I propose that we introduce accessor functions for all slots in the MizerParams and MizerSim objects that a user might want to access. That isolates the user from the internal representation and leaves us free to change the internal workings of mizer in the future. 

We have to decide how to name the functions. So for example, if the user wants to get at the metabolic rate in a model described by a MizerParams object called `params`, do they prefer to use
`getMetab(params)` or  `getMetabolicRate(params)` or simply `metab(params)` (because the slot is `@metab')? For the maximum intake rate, do we want `getIntakeMax()` or `getMaxIntakeRate()` or `intake_max()`? And so on. Any views? It would be ideal if the names were chosen by a fisheries person rather than by me as a mathematician.

Given RStudio's ability to autocomplete, I am leaning towards the longer and more explicit names. Of course the corresponding setter functions should then use the same, so `setIntakeMax()` would become `setMaxIntakeRate()` to go with `getMaxIntakeRate()`.

Also, would we be happy to use `n(sim)` and `n_pp(sim)` to get at the abundances of fish and plankton in a MizerSim object called `sim` or would we like to use the opportunity to choose a better name than `n_pp`?

Note that I am not proposing to prevent users who are already used to accessing the slots directly to continue to do that. I just want to use the new form in the documentation to encourage new users to use is because it isolates them from the implementation.

**Comment by Kenhasteandersen** [comment]
Using slots is a very good idea, exactly because it encapsulates the inner working in a consistent outer interface for the user. I also prefer the longer names with the “get” prefix.

Also, would we be happy to use n(sim) and n_pp(sim) to get at the abundances of fish and plankton in a MizerSim object called sim or would we like to use the opportunity to choose a better name than n_pp?

How about nResource? The PP refers to Primary Production, which is badly chosen because fish don’t eat primary producers.

Ken


Note that I am not proposing to prevent users who are already used to accessing the slots directly to continue to do that. I just want to use the new form in the documentation to encourage new users to use is because it isolates them from the implementation.

**Comment by gustavdelius** [comment]
I went for `N()` and `NResource()` because `n()` is already used by the tidyverse. There are no accessor functions for all other relevant slots.

**Comment by juliablanchard** [comment]
Yes, good call since most folks will also use tidyverse.

________________________________
