### ISSUE TITLE
Remove `sex_ratio` arguments

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#153]
Since its inception, Mizer has had a `sex_ratio` argument to the `getRDI()` and `getRDD()` functions, but the `project()` function had the value of this parameter hard-coded to `sex_ratio = 0.5` and so the user had no way of changing the sex ratio in simulations. I propose to remove that `sex_ratio()` argument from core mizer. In a mizer extension the sex ratio could become a species parameter if anyone is interested. This proposal is in the vein of keeping the core mizer simple.

**Comment by Kenhasteandersen** [comment]
Agree. Ken
---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New book: Fish Ecology, Evolution, and Exploitation - A New Theoretical Synthesis https://press.princeton.edu/titles/13516.html


[cid:image001.jpg@01D09493.A377DFB0]

On 5 Mar 2020, at 13.26, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


Since its inception, Mizer has had a sex_ratio argument to the getRDI() and getRDD() functions, but the project() function had the value of this parameter hard-coded to sex_ratio = 0.5 and so the user had no way of changing the sex ratio in simulations. I propose to remove that sex_ratio() argument from core mizer. In a mizer extension the sex ratio could become a species parameter if anyone is interested. This proposal is in the vein of keeping the core mizer simple.
