### ISSUE TITLE
Pass name of component to component dynamics function

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#164]
Via `setComponent()` users can add an extra dynamical component and specify via the `dynamics_fun`, `encounter_fun` and `mort_fun` the functions that describe the behaviour of the component. Sometimes users may want to add several very similar components and may want to avoid having to write a new set of functions for each component. For example there may be several resource components all using semi-chemostat dynamics. The proposal therefore is to pass the name of the component to these functions so that the same function can do the appropriate thing for each component.

**Comment by astaaudzi** [comment]
Yes, this sounds like a good idea and would be useful, although not such a big deal to repeat the same code for a few components. This would only have to be done once anyway, when setting up a model. Unless people want to have a separate background spectrum for each species. 
Thanks for all the new functions to facilitate extensions

**Comment by gustavdelius** [comment]
@astaaudzi Thanks for you comments. I already committed the change.

**Comment by astaaudzi** [comment]
@gustavdelius  thanks for the edits to the extension code. 

We have tried to apply this with @camillanovaglio and got an error. Here is the code we used to try and add a background benthos spectrum resource: 

#get the latest mizer 
devtools::install_github("sizespectrum/mizer")
#use North Sea model 
params <- NS_params

#look at the plankton resources params 
params@resource_params$kappa
params@resource_params$lambda
params@resource_params$r_pp #
params@resource_params$n ## 
params@resource_params$w_pp_cutoff  

# Set up parameters for a new spectrum
kappa <- 0.005 
lambda <- 2.05 
r_pp <- 0.1
n <- 0.666 
w_pp_cutoff <- 10

## we understand that we need to pass capacity and rate into the resource_dynamics function. We tried both ways - see below
rate <- r_pp * params@w_full^(n - 1)
capacity <- kappa * params@w_full^(-lambda)
capacity[params@w_full > w_pp_cutoff] <- 0

# now we use the available functions in mizer to define the new component called background_bb

params2 <- setComponent(params = params, component = "background_bb", initial_value = params@initial_n_pp, dynamics_fun =  params@resource_dynamics, encounter_fun = params@rates_funcs$Encounter, mort_fun = params@rates_funcs$ResourceMort, component_params = list(rr_pp = rate, cc_pp = capacity))

## Or we actually specify original parameters of the resource, like kappa, lambda, etc (both ways return an error)
params2 <- setComponent(params = params, component = "background_bb", initial_value = params@initial_n_pp, dynamics_fun =  "resource_semichemostat", encounter_fun = "mizerEncounter", mort_fun = "mizerResourceMort", component_params = list(kappa = kappa, lambda = lambda, r_pp = r_pp, n = n, w_pp_cutoff = w_pp_cutoff))

#just check how our new component looks 
getComponent(params2, "background_bb")
#looks ok, has all the functions, initial values, rr_pp and cc_pp defined

#Now we update rate functions for encounter and mortality
params2 <- setRateFunction(params2, "Encounter", "mizerEncounter")
params2 <- setRateFunction(params2, "Mort", "mizerResourceMort")

newSim <- project(params2, t_max = 75, effort = 0)

#we get an error
# Error: node stack overflow
# Error during wrapup: node stack overflow

Are we doing something completely wrong here??  Do we need to specify and pass our own functions here, as was required previously? We thought we can now refer to the existing functions in mizer, but perhaps that was not the intention? 

A few more questions: 
1) How do we specify the minimum size of the new spectrum, if we don't want it to start at the minimum plankton size? 
2) How do we pass to the functions a new species_params$interaction_other_benthos vector instead of $interaction_resource
3) In the size spectrum plot we want to see all background spectra, not only the plankton spectrum. Or what we would see is the sum of the two spectra? 

Is it too much to ask? 

thanks :)

**Comment by astaaudzi** [comment]
oops, did not mean to make the font so big for some lines :)

**Comment by gustavdelius** [comment]
Hi Asta @astaaudzi . Thanks for posting your question here. That is indeed better than private emails which can easily get lost. I had already sent the answer to Camilla @camillanovaglio: you need to define your own dynamics and encounter function. You can not use the one written especially for the built-in resource. Here is the code I sent to Camilla, but now edited to use your example of the North Sea model and to use a component-specific interaction vector.
```
background_bb_semichemostat <- function(params, n_other, rates, dt, ...) {
    component <- "background_bb"
    c <- params@other_params[[component]]
    # name of interaction parameter for this component in species_params
    interaction_component <- paste0("interaction_", component)
    interaction <- params@species_params[[interaction_component]]
    mort <- as.vector(interaction  %*% rates$pred_rate)
    tmp <- c$rate * c$capacity / (c$rate + mort)
    return(tmp - (tmp - n_other[[component]]) * exp(-(c$rate + mort) * dt))
}

background_bb_encounter <- function(params, n, n_pp, n_other, ...) {
    mizerEncounter(params, n = n, n_pp = n_pp + n_other$background_bb, ...)
}

params <- NS_params

# Set up parameters
kappa <- 0.005
lambda <- 2.05
r_pp <- 0.1
n <- 0.666
w_pp_cutoff <- 10
rate <- r_pp * params@w_full^(n - 1)
capacity <- kappa * params@w_full^(-lambda)
capacity[params@w_full > w_pp_cutoff] <- 0

# Also have a minimum size of the new spectrum
w_pp_min <- 1e-6 # You choose a value
capacity[params@w_full > w_pp_cutoff] <- 0

# We also use an interaction vector stored in the species_params data frame
# with a name made out of the component name.
# I'll set it here to the same as the one for the built-in resource, but
# you will want to change that
params@species_params$interaction_background_bb <- 
    params@species_params$"interaction_resource"

params2 <- setComponent(params = params, component = "background_bb",
                        initial_value = params@initial_n_pp,
                        dynamics_fun =  "background_bb_semichemostat",
                        component_params = list(rate = rate,
                                                capacity = capacity))
params2 <- setRateFunction(params2, "Encounter", "background_bb_encounter")

sim2 <- project(params2, t_max = 75, effort = 0)
```
By the way: to include code in a post like this you can use the "< >" button on the post editor toolbar.

To plot the results you will need to write your own plot function. You can of course use the built-in plot functions to get a ggplot2 object to which you then only need to add the extra stuff for your new components.

**Comment by astaaudzi** [comment]
Thanks, @gustavdelius. We misunderstood, thinking this new issue allows using existing functions. Now it is clear, thanks. It should work now. And having the example code here is useful for other I guess

**Comment by juliablanchard** [comment]
Thanks for this all, I really like the flexibility and generality of this approach.

 I think we’ve discussed it previously and forgive me if I’ve forgotten but @gustavdelius I wondered whether there a reason why setting the number of resource spectra (when they do all have the same dynamics and just different parameters) couldn’t be part of core mizer new param functions ?

I think this is something most users would find useful...and I think several have implemented in their own offline code?

Probably a separate issue but maybe a survey of what features would be useful to have implemented in / out of core mizer  might also be helpful form of feedback for this sort of thing  (maybe for the next version)?

Any thoughts?

________________________________

**Comment by astaaudzi** [comment]
@juliablanchard, my impression was that it was decided to keep the core mizer simple and easy to use, with additional functionality added as plug-ins. So @gustavdelius have the unstructured resource plug-in, we have starvation mortality extension, soon (hopefully) multiple size structured resources available, then - temperature effects, also evolution, fleet dynamics, perhaps also seasonality? This way the key mizer stays easy to use and relatively stable, and new functionality is optional. Of course the key challenge will be to ensure that different extensions integrate with each other (i.e. if someone wants to add evolution, temperature and multiple background spectra).

**Comment by camillanovaglio** [comment]
Thanks for this @gustavdelius, and sorry my mistake - I thought this issue was raised after our email conversation to allow using existing functions for the background. Also thanks for showing how we can change interaction_resource and w_pp_cutoff for the additional resource component.

**Comment by gustavdelius** [comment]
@juliablanchard The consensus at the mizer meeting seemed to be as Asta described, namely to keep core mizer lean and implement anything that does not require a modification of the core in a mizer extension. However, once a particular extension becomes widely used and is mature, a discussion of whether to move it to core will certainly be appropriate. We don't want to do that too early, partly to get people more used to the idea of using mizer extensions. Every advanced user should at least be installing the MizerExperimental extension and if they find some functionality there that they really like, they can suggest that it should be moved to core, at least once the feature is mature and stable.

**Comment by juliablanchard** [comment]
@gustavdelius thanks for jogging the memory, yes agree it makes sense to hold off, get folks trying these features out soon - hopefully we will have a few extensions over the next few months and will be able to see how this develops.

________________________________
