### ISSUE TITLE
newMultispeciesParams

### ISSUE THREAD

**Issue by yuxinch** [sizespectrum/mizer#184]
Is there a difference in calculating the default value of the parameter using newmultispeciesParams () versus using the old version of MizerParams ()?When I use the same set of parameters to calculate, the default h and gamma values calculated by the two are quite different.If possible, I want to know the formulas for get_h_default and get_gamma_default in newMultispeciesParams ().

**Comment by gustavdelius** [comment]
Yes, they are different. 

The new version chooses `gamma` so that if the prey abundance was described by the resource power law, then the encounter rate would lead to the feeding level `f0`. It then chooses `h`, the coefficient in the maximum intake rate, so that the species reaches maturity size at the age predicted by the von Bertalanffy growth curve parameters.

The default 'gamma' is calculated here:
https://github.com/sizespectrum/mizer/blob/54e93bc88d8781e9a2befbd16fe7dd742d6a0eb7/R/species_params.R#L241-L246

and the default 'h` is calculated here:
https://github.com/sizespectrum/mizer/blob/54e93bc88d8781e9a2befbd16fe7dd742d6a0eb7/R/species_params.R#L191-L193

**Comment by yuxinch** [comment]
Thank you very much for your guidance. Wish you all the best in your work.






------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "sizespectrum/mizer"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月18日(星期四) 晚上9:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [sizespectrum/mizer] newMultispeciesParams (#184)





 
Yes, they are different.
 
The new version chooses gamma so that if the prey abundance was described by the resource power law, then the encounter rate would lead to the feeding level f0. It then chooses h, the coefficient in the maximum intake rate, so that the species reaches maturity size at the age predicted by the von Bertalanffy growth curve parameters.
 
The default 'gamma' is calculated here:
 https://github.com/sizespectrum/mizer/blob/54e93bc88d8781e9a2befbd16fe7dd742d6a0eb7/R/species_params.R#L241-L246
 
and the default 'h` is calculated here:
 https://github.com/sizespectrum/mizer/blob/54e93bc88d8781e9a2befbd16fe7dd742d6a0eb7/R/species_params.R#L191-L193
