### ISSUE TITLE
Difference between metabolic rate and activity rate

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#22]
The mizer code is currently differing from the mizer vignette is some places. One of them is that the mizer code subtracts both the energy needed for metabolic activity $k_{s.i} w^p$ and the energy needed for other activity (movement) $k w$, whereas the model presented in chapter 3 of the vignette only has the former. Is there an argument why the energy cost of movement scales linearly with weight?

**Comment by Kenhasteandersen** [comment]
Yes, there is some indications that activity scales with a higher exponent that metabolism from the work by Daniel Ware in the 70s. However, I rarely use that option and set the weight-specific constant = 0.  The problem is, that I do not know how the constant for activity would scale with asymptotic size.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk

New online app: Fish community simulator http://oceanlife.dtuaqua.dk/cspectrum.

[cid:image001.jpg@01D09493.A377DFB0]

On 7 Dec 2017, at 19.42, Gustav W Delius <notifications@github.com<mailto:notifications@github.com>> wrote:


The mizer code is currently differing from the mizer vignette is some places. One of them is that the mizer code subtracts both the energy needed for metabolic activity $k_{s.i} w^p$ and the energy needed for other activity $k w$, whereas the model presented in chapter 3 of the vignette only has the former. What is the use case for the energy loss rate $k w$ that scales linearly with the weight $w$? Is there an argument why some activity scales linearly with weight?

**Comment by gustavdelius** [comment]
Thanks Ken. For now I simply updated the vignette to reflect that mizer implements an activity rate that scales linearly with weight. As you say, people don't have to use it and it is switched off by default.
