### ISSUE TITLE
`setBevertonHolt()` does not respect `erepro` input

### ISSUE THREAD

**Issue by patricksykes** [sizespectrum/mizer#244]
It is currently not possible to guarantee that `setBevertonHolt()` (and functions that rely on it, such as `newTraitParams()`) will respect the user's inputs for `erepro` and `R_max`. This is particularly an issue for `erepro`, which `setBevertonHolt()` is liable to set to unrealistic values greater than 1 despite the user specifying a value of 1 or less.

The [documentation](https://sizespectrum.org/mizer/reference/setBevertonHolt.html) says
>The values for `erepro` must be large enough to allow the required reproduction rate. If a smaller value is requested a warning is issued and the value is increased to the smallest possible value. The values for `erepro` should also be smaller than 1 to be physiologically sensible, but this is not enforced by the function.

However, I believe it should be possible to enforce this requirement.

**Comment by patricksykes** [comment]
Hi Gustav,

I see I must have been using the `setBevertonHolt()` function in the incorrect context - to set up the `R_max` parameter for a new ZooMizer run, rather than applying to an existing steady-state model. I still think though that the function should at least allow the user to specify that the value of `erepro` must be physically sensible, that is, less than or equal to 1. In my case, I specified `erepro = 1` in the function call, and ended up with values ranging from about 5 to 200000.

For a little more context, I want to find reasonable `erepro` and `R_max` values for a range of chlorophyll inputs to ZooMizer. Having found that, as you said, `newTraitParams()` sets unrealistic values for `erepro` (even for quite high values of `reproduction_level`), I resolved to set `erepro` to 1 and look to tune the `R_max` using `setBevertonHolt()`. Is there another way to do so?

For now, I am setting the `erepro` and `R_max` values in ZooMizer by hand (to 1, and by an allometric relationship from the North Sea model: `kappa * w_inf^(-1.5)`, respectively) but am finding that reproduction is higher than I would like for low chlorophyll and a too low at high chlorophyll relative to the biomass of the zooplankton resource. When I say reproduction is too high/low, I mean that fish eggs vastly outnumber the zooplankton spectrum for low chlorophyll (where the zooplankton spectrum is already relatively low) and the reproduction level is very low (on the order of 1e-10) and conversely at high chlorophyll, the reproduction level is sitting at or just below 1.

Do you have any suggestions on how to tune the `R_max` for different resource inputs, if `setBevertonHolt()` is not the right function to use here?

**Comment by gustavdelius** [comment]
Let us back up a bit and reflect on what the reproduction parameters are for. There is a two-dimensional space of parameter values. Itt is probably better to parametrise that no by `erepro` and `R_max` but by the rate of egg production and the reproduction level. The rate of egg production determines the abundance of your species. The reproduction level determines how sensitive the model is to perturbations. I calibrate a model in two steps. In the first step I get the steady state to agree with observations, in particular to have the abundances that are observed. For that I only need to tune the rate of egg production in that steady state. In the second step I get the model to have the desired sensitivity to changes in for example fishing pressure. For that I only need to change the reproduction level. If I do that using `setBevertonHolt()` then that second step does not mess up my first step because it does not affect the steady state.

Now I believe that you are working on the first step of getting an acceptable steady state. At that step I would set the reproduction level to 1 (which is equivalent to R_max = Inf). If in the process of getting your fish species to have the observed abundances you get an `erepro > 1` then that means that there are problems elsewhere in your model. It means the species as modelled are just not viable. Perhaps they are not getting enough food or perhaps they experience too high mortality. 

To answer your last question: don't tune `R_max` at all but leave it at `Inf` (set `reproduction_level = 1`). Use `erepro` to adjust the abundances of your species (with `species_params(params)$erepro <- `). When an `erepro` gets above 1 for some species, given them more to eat or reduce their mortality.

**Comment by patricksykes** [comment]
Thank you for sharing your workflow for calibrating a model. I wonder how that differs in the case of ZooMizer where there is no data to fit to, rather we are interested in the kind of fish community that arises under different environmental conditions (and, in particular, differently-structured zooplankton communities). The current situation is that not all of the trait-based model species are surviving under all conditions. Often the planktivores lack food under low nutrient conditions, and in general a group or two will go extinct under most conditions I believe due to predation pressure and the competition for resources.

I will try your suggestion of first setting the reproduction level first to 1 (or rather 0.9999, since `reproduction_level = 1` throws an error - is this expected behaviour?) and then adjusting the abundances with `erepro`.

**Comment by patricksykes** [comment]
Hi Gustav,

I have run the model again with `reproduction_level = 0` and a higher value for `alpha` (the value used in Ken Andersen's book is 0.6). Combined, these allow the `erepro` to come out as less than 1. Ideally, I would like to have some density-dependence in reproduction though. Supposing I start with `reproduction_level = 0` and obtain a steady state that's working for me, would that be the time to use `setBevertonHolt()`, specifying a `reproduction_level` greater than 0?

**Comment by gustavdelius** [comment]
Yes, but if you raise it too high (or lower `R_max` to far), then `erepro` will get above 1 again.
