### ISSUE TITLE
What units to use in mizer

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#42]
Mizer is really mostly unit agnostic, i.e., the user gets to choose the units they like best when they calibrate the system. However the defaults are set up with grams and years in mind as weight and time units and in the newer versions of mizer some plots put these units on the axes. 

The current situation is a bit confusing for users, as Chris Griffiths has just pointed out to me.

Should we make the situation less confusing by imposing the use of grams for sizes and for biomass and years for time? Or do we want to let the user make the choice? In the latter, do we want to store the choice of units in the params object so that the plot functions can label the axes appropriately? I am leaning towards the simpler solution of imposing units. Then the documentation of functions like getYield can be made clearer by saying that it returns the yield in grams per year.

A related issue is the question of whether all rates and abundances should be seen as per volume or for the entire study area. Here I think different users might have different preferences. I guess specifying rates and abundances per volume is a bit problematic because one needs to decide to which depth to go when determining the volume of the study area. Any comments?

**Comment by Kenhasteandersen** [comment]
Dear Gustav,

Thanks for bringing this up on the mailing list.

A related issue is the question of whether all rates and abundances should be seen as per volume or for the entire study area. Here I think different users might have different preferences. I guess specifying rates and abundances per volume is a bit problematic because one needs to decide to which depth to go when determining the volume of the study area. Any comments?

The issue is the unit of abundances.

1) They can be given in absolute units, i.e., just numbers or numbers/mass for the number spectrum
2)  In volume concentrations, i.e., numbers per volume
3) In “per area”, i.e., numbers per area

That choice then determines the units of the clearance rates, which will be “per time” (case 1), “per volume per time” (case 2), or “per area per time” (case 3). Similarly integrated measures, such as the yield, will have different units (mass, mass per volume, and mass per area respectively).

I use any of the three formulations, depending on the case. Clearly, if you use case 3, you need to multiply with the area of the ecosystem to get the total yield. If you work with case 2, you need to multiply by both area and the thickness of the productive layer. In that respect, case 2 is a bit cumbersome.

Ken

**Comment by juliablanchard** [comment]
I think it’s best to be explicit about the units in all functions and outputs  and to make this clearer to the user and probably best to keep fixed as is? We could then just explain how to scale up to if that is desired ( via kappa etc) ...

Sent from my iPhone
________________________________

**Comment by gustavdelius** [comment]
Hi @juliablanchard , I agree with you that it would be simplest to dictate that the user should use grams and years as the units for weight and time, rather than letting the user choose the units. @Kenhasteandersen 's reply confirmed my belief that we do not want to dictate to users whether they want to view abundances and rates as per area, per volume or per study area. Instead we will just discuss this issue clearly in the documentation, as Ken has done in his reply above.

**Comment by juliablanchard** [comment]
Hi both, yes - I agree that makes sense.

________________________________

**Comment by astaaudzi** [comment]
Thanks for this discussion. I have also been wondering and getting confused about the units... 

I agree with the others that it is good to have the option to chose. But it would be good to explain this clearly in the vignette, because I myself got quite confused at the start. At the moment I have settled on using m2, and to my understand this would affect: 
a) kappa, which now becomes an intercept of the background resource slope measured in g/m2 
b) gamma, or search rate/area, which becomes m2/g*year (where g is unit of predator body mass scaled by the search rate exponent)
c) The realised biomass and abundance will then be given as grams or individuals per m2. By the way, one thing I have been confused about for a while is that model@n or model@n_pp does not actually give numbers in each size group, but numbers per gram in each size group. So to get the actual numbers one should multiply them by params@dw or params@dw_full. I am sure this is explained in the vignette or papers, but it might be good to make it clearer in the mizer vignette "unit" section :)

**Comment by Kenhasteandersen** [comment]
Dear Asta,

Your understanding of the units is perfectly correct.

The vignette might need at paragraph that explains a “normalised” size spectrum and how one integrates the spectrum to get population-level quantities such as the biomass or total number of individuals.

Ken

---------------------------------------------------------------------------------------------------------------
Ken H. Andersen, http://ken.haste.dk<http://ken.haste.dk/>, twitter: @69kno
Professor in theoretical marine ecology, head of section, and deputy director of Centre for Ocean Life http://www.oceanlifecentre.dk<http://www.oceanlifecentre.dk/>

New paper: A trait-based approach to ocean ecology<https://www.google.com/url?q=https://academic.oup.com/icesjms/advance-article/doi/10.1093/icesjms/fsy090/5056134&sa=D&sntz=1&usg=AFQjCNFVkw1WnenGUFvOaKHEPxp8I30XKA>. ICES Journal of Marine Science 2, 65–70 (2018)

[cid:image001.jpg@01D09493.A377DFB0]

On 6 Mar 2019, at 23.58, Asta Audzi <notifications@github.com<mailto:notifications@github.com>> wrote:


Thanks for this discussion. I have also been wondering and getting confused about the units...

I agree with the others that it is good to have the option to chose. But it would be good to explain this clearly in the vignette, because I myself got quite confused at the start. At the moment I have settled on using m2, and to my understand this would affect:
a) kappa, which now becomes an intercept of the background resource slope measured in g/m2
b) gamma, or search rate/area, which becomes m2/g*year (where g is unit of predator body mass scaled by the search rate exponent)
c) The realised biomass and abundance will then be given as grams or individuals per m2. By the way, one thing I have been confused about for a while is that model@n or model@n_pp does not actually give numbers in each size group, but numbers per gram in each size group. So to get the actual numbers one should multiply them by params@dw or params@dw_full. I am sure this is explained in the vignette or papers, but it might be good to make it clearer in the mizer vignette "unit" section :)

**Comment by gustavdelius** [comment]
Does anyone now what units were chosen when the default values for various rates were chosen in `set_community_model()` and `set_trait_model()`? 

`set_community_model()` chose `kappa = 1000` with `lambda = 2 + 2/15` and `r_pp = 10`.

`set_trait_model()` chose `kappa = 0.005` with `lambda = 2 + 7/30` and `r_pp = 4`.

Do these make sense if I think of abundance per m^2 or km^2 or what?

**Comment by gustavdelius** [comment]
Just saw that the value for `kappa = 0.005` in the trait model probably comes from Hartvig et. al 2011, although they use a different value for `lambda`. That paper works with abundance per cubic meter.
