### ISSUE TITLE
Save mizer version and metadata in MizerParams object

### ISSUE THREAD

**Issue by gustavdelius** [sizespectrum/mizer#45]
We should add a `mizer_version` slot to the MizerParams object which holds the version of the mizer code with which the params object was created. That way the results from simulations performed with that model will remain reproducible in the future by just checking out that version of the mizer code from github. It would also allow us to selectively enable new features of mizer only for params objects that support them, or to upgrade an old params object to a new version of mizer. Thanks to @astaudzi for bringing up this issue.

We might also want to add a `repo` and a `ref` slot, so that users can indicate that a params object is to be used with code in another repository or from a particular commit or tag. This can then be used together with [install_github()](https://www.rdocumentation.org/packages/devtools/versions/1.13.3/topics/install_github)

While we are at it, how about also adding a `title` and a `description` slot, to make it easier for people to remember what their params objects were for and a `creation_time` slot because why not and it can be populated automatically and may help people later to know which is their latest version.

Because at a later stage we might want to start a repository of mizer models contributed by different users, I also propose to add an `author` and an `orcid` slot, the former for a human-readable author name, the latter for their ORCID id.

Finally it would be good to know whether a params object is a community model, a trait-based model, a multi-species model or some other model for which setup functions may be developed in the future. We could store this info in two ways: either in a `setup_fun` slot that holds the name of the setup function, or   in the class of the object, if in addition to the MizerParams class we introduce subclasses CommunityModel, TraitModel, MultispeciesModel, etc. I don't see a benefit of the latter approach, so I think I am leaning towards the more straightforward former approach.

**Comment by astaaudzi** [comment]
Great idea, and an important step I think. I also love the idea of the repository of mizer models. This will help the development of new models and make model outcomes and results more reproducible.

**Comment by juliablanchard** [comment]
I completely agree - these are all great and important advances for reproducibility and also further open source community development. I also love the repository of mizer models - I’ve been calling the different models so far an  ‘ecosystem of mizer models’ :)

Thanks for the other resolutions, changes and updates as well @gustavdelius!

Sent from my iPhone
________________________________

**Comment by gustavdelius** [comment]
I have changed my mind on this. I do not think that the way to share models is via their MizerParams objects. Instead they should be shared in the form of an R notebook that contains the code for setting up that MizerParams object using the functions mizer provides for that purpose. 

The reason is that the structure of MizerParams class will keep changing as we introduce new features into mizer that require changes to the slots. Old MizerParams objects will then cease to be valid MizerParams objects. We can keep backwards compatibility for the functions that mizer provides, but not for the MizerParams class.

The other big advantage of sharing models in the forms of R notebooks that set up the models is that the notebooks will contain a lot of interesting human-readable information about the model. At some point we might want to provide a template for such an R notebook that guides contributors on what information to include and how.

**Comment by astaaudzi** [comment]
@gustavdelius, I agree that R notebooks or R markdown would be a good way to share models, but it requires additional effort from people and is unlikely to happen (because it has not happened so far). In contrast, uploading a MizerParams object is easy and takes almost no extra effort. So:
1) if the MizerParams object stores the version of mizer used for the model and, 
2) if it is easy to download earlier specific versions of mizer from github or cran, 
this is all we need to make earlier studies reproducible. 

If people are interested in adapting earlier mizer models for new mizer versions, it can be done as a part of model comparison effort. It is not that difficult to extract all the required information from the MizerParams list if one needs to update the structure (certainly easier than going to the old papers and copy-paste parameters and then try to guess other parameters that may not have been listed in the paper but set by default, like r_pp). 

Of course it does not preclude R notebooks or other ways to share models. Both can be done and the most dedicated users will use them. But we should make it as easy as possible. Ideally there would be a rule that publications using mizer are not accepted until the model is uploaded to a repository :) (like it is done with genetic work)

**Comment by gustavdelius** [comment]
More thought about the `version` slot. I think it should be updated only when a MizerParams object is saved (with `saveParams()`, see #171). The reasoning is that one would only save MizerParams objects when they work, so the version that last saved it should be a version in which the MizerParams object will work. That is the only important purpose of the `version` field: to identify a version of mizer in which the model will run as intended.

**Comment by gustavdelius** [comment]
I decided against introducing a `title()` function because this would overwrite `graphics::title()`. The of course it also does not make sense to have `description()` and `version()` makes no sense because the version will be set automatically. So the only way to set metadata by hand will be via `setMetadata()`.

**Comment by gustavdelius** [comment]
To see what finally got implemented look at https://sizespectrum.org/mizer/dev/reference/setMetadata.html
