### ISSUE TITLE
Setting up multiple gears per species

### ISSUE THREAD

**Issue by michaelspence** [sizespectrum/mizer#83]
We propose to allow the user to input fishing gears and parameters as an additional input to the MizerParam function. The data frame will contain a species object, where the user specifies one species to be caught by a particular gear; a gear object, where the user specifies a gear name; a catchability function, where the user specifies the function used to generate the catchability curve; maximum catchability, defining the maximum catchability of that species with that gear, and parameters of the catchability curve. The same species can appear in different rows of the data frame with different gears.

**Comment by gustavdelius** [comment]
Some background to this: core mizer was always set up to allow any species to be caught by an arbitrary number of gears, however the user would need to set the `selectivity` and `catchability` arrays in the MizerParams object by hand, because the `MizerParams()` setup function only allowed one gear per species. This proposal would make it easier to set up multiple gears per species.

The data frame described by Mike would be passed to the function `setFishing()` via a new `gear_params` data frame. After the function has used the information from the data frame to set up the `selectivity` and `catchability` arrays, we could store the data frame in the params object, as we do for the species_params data frame, or we could discard it. What do you think would be better.

**Comment by juliablanchard** [comment]
I agree having the flexibility for multiple gears per species has been missing and is really needed. Might also be worth checking in with @camillanovaglio who has been working on multiple (and overlappping) fleets to see how she has been doing this

**Comment by camillanovaglio** [comment]
Hi all, I apologise for the lengthy response. Lost to say. Happy to move this to an email conversation if best. 

Just as a note, in my version of the model fleets can target multiple specie and each fleet is driven by economic factors (profit) so that model forcing are species-specific prices and fleet-specific costs instead of effort. I haven’t fully implemented and tested the in-between level where model forcing are fleet-specific effort values. But a couple of colleagues I am working with on the development of Mizer models for different systems and their use to answer fisheries management questions would like to use this version. So, my plan is to test it soon (and this conversation is great).

I used a similar approach to the one discussed here. I grouped Mike’s inputs into 2 objects: a fleet X species matrix (_catchability_) specifying which species each fleets targets and by how much – i.e. 0 if the species is not a target of the fleet and 1 if the species is fully accessible to the fleet, similar to the interaction matrix; and a df (_selectivity_params_) that specifies the gear, selectivity function and params for each species and fleet combination (please see below). 

I pass both _selectivity_params_ and _catchability_ to MizerParams() and store them in the params object. _catchability_ will be used in project to calculate mortalities, but _selectivity_params_ could actually be discarded once used in this function. When setting res@selectivity in MizerParams() the for loops are by fleet and by species (instead of by gear/fleet only, I think). 

_selectivity_params_ example. The ‘gear’ field calls the selectivity function as in the original Mizer. Options are knife edge, sigmoid (called trawl) and bell-shaped (called gillnet)    
    subfleet                   species            gear       param_name   param_value
1        SSG       centroberyx affinis      gillnet      W25_S           165.90832
2        SSG          seriolella brama       gillnet      W25_S            216.44249
3        SSG       genypterus blacodes gillnet      W25_S            1714.26800

_Catchability_ example. 
       centroberyx affinis galeorhinus galeus genypterus blacodes helicolenus barathri
SED           0.0001980472       0.0001508034         0.002055938                    0
SET-DS        0.0000000000       0.0000000000         0.017267002                    0
SET-SH        0.2227905060       0.0024284621         0.068479466                    0
SET-US        0.0764004775       0.0044350325         0.902269349                    0
SSG           0.0006109693       0.0929857021         0.009928245                    0
 
Inside project(), the main changes relate to the effort matrix (time X fleet), the calculation of fishing mortality for each species targeted by multiple fleets, and of yield by fleet. Fishing mortality for each species is calculated as the sum of mortalities from each fleet targeting the species. So first at fleet level: Fmort_fleet = effort (cost) * Q (catchability) * selectivity (selectivity_params). Fmort_fleet is also used to calculate yield by fleet. 

Happy to discuss more and collaborate on this, Cami

**Comment by gustavdelius** [comment]
Thank you for that very informative post. This issue tracker is exactly the right place for such in-depth discussions of features.

If I understand correctly, what you call "fleet" is exactly the same as what mizer misleadingly calls "gear", namely something that catches multiple species with possibly different selectivity curves for each species, and for which a time-dependent effort can be specified. You calculate the fishing mortality the same way as mizer currently does, see https://sizespectrum.org/mizer/dev/reference/MizerParams.html#setting-fishing , just with the sum over gears being a sum over fleets. Please tell me if I misunderstood.

You and @michaelspence  have a slightly different proposal for how to specify the parameters needed to set up the selectivity array and the catchability matrix. The two main differences are:

1. In your proposal the user specifies the catchability matrix directly (albeit as a data frame, but that does not make any difference), whereas in Mike's proposal that information is included in the data frame.
2. In your proposal there is one column for the parameter names and one for the parameter values, and then one row in the data frame for each parameter for each gear/fleet and species. In Mike's proposal there is one column for each parameter name, holding the value of that parameter. Mike's proposal leads to many NAs in the data frame because not all parameters are used by all selectivity curves.

Personally I think your proposal is the more elegant (and I should admit that I am responsible for the inelegance in Mike's proposal that we came up with together during a bus ride).

I also prefer your term "fleet" to mizer's current term "gear".

When implementing the new way of setting up the selectivity and catchability arrays, please keep the old way around for backwards compatibility. In the documentation we will however indicate that it is deprecated.

**Comment by camillanovaglio** [comment]
@michaelspence @gustavdelius I think MIke's table for selectivity is best. Mine is the same but after a gather(), which I could have called inside MIzerParams(). And, I do have lots of NAs too. It seems more intuitive for the user to fill in selectivity info for each fleet-species combinations by columns. 

I am not sure what the 'selectivity' column in the table above is. Should that be catchability? In my experience it is better to have a separate fleet by species matrix/df with catchabilities only. This is because catchabilities are most often key parameters that need tuning/calibration, and it's handy to have them on a separate file and to be able to clearly compare values across fleets and species while tuning. 

I like fleets better than gears too. Right now fleets and gears have the same meaning, but a further extension might be multi-fleet and multi-gear, where each fleet (e.g. the pelagic fishing fleet) can 'choose' to use different gears (e.g. longline or pelagic trawl). This is actually similar to fleet and sel_function in the table above. Instead, in my version each fleet (e.g. the trawling fleet) uses one gear (trawl) characterised by one selectivity function (sigmoid_weight). I think sel_function should be gear-specific.  

I saw that this issue is closed - how do we go from here? Should I keep working on my version and keep you updated on any progress while you implement this in Mizer? 

Cheers, Cami

**Comment by gustavdelius** [comment]
@camillanovaglio , you are right, the column heading in the example table should have been "catchability". I have now corrected that.

I am not yet convinced that every user will want to set up two separate spreadsheets. This may be useful for some users with complicated setups, but for simpler cases it would be an unnecessary complication. However I am not opposed to giving the user the option of either including the catchability in the single data frame or to provide it separately in a second data frame.

Let us not put the extension to several gears per fleet into core mizer. This could be a mizer extension in the future.

This issue is not closed. I closed the corresponding issue on my fork in order to concentrate the discussion onto this issue here, and GitHub displayed that event in a somewhat confusing fashion.

As to how to progress this: perhaps the best would be for each of you to look at the other's code and then one of you to take the lead to combine the best bits of each and integrate them into mizer. The code should go into the `setFishing()` function in mizer.

**Comment by camillanovaglio** [comment]
Sounds all good, having one file with all fishing parameters makes things simpler. Though I do like your second option too.

My codes are in camillanovaglio/mizer-fleet (messy).

**Comment by gustavdelius** [comment]
Yes, I think we should keep all three options for setting the fishing:

1. Via columns in the species_params dataframe, as currently. This restricts to at most one gear per species.
2. Via a single fleet_params dataframe, as proposed by Mike
3. Via two dataframes. as proposed by you.

Which method is used will depend on what the user passes to the `setFishing()` function.

**Comment by gustavdelius** [comment]
Besides adding code to `setFishing()`, we should also reword all mention of "gear" in the vignettes and in the documentation to refer to "fleet" instead.

**Comment by gustavdelius** [comment]
@michaelspence and @camillanovaglio, have you done further work on this? Mariella and I are going to give a mizer course in Santiago, Chile next week and it would be nice if we could already teach them the new way of setting fleet parameters.

**Comment by gustavdelius** [comment]
I have now implemented this via a new slot `@gear_params` in the MizerParams class. See https://sizespectrum.org/mizer/dev/reference/setFishing.html#setting-fishing. Thanks go to @camillanovaglio and @michaelspence for pushing for this and providing code. I used their code for inspiration.
